import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/Link'
import { colors } from '../styles/theme'
import {useRouter} from 'next/router'
import AppLayout from '../components/AppLayout'
import Button from '../components/Button'
import GitHub from '../components/Icons/GitHub'

export default function Home() {
  const router = useRouter();
  console.log(router);
  return (
    <>
      <Head>
        <title>devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <AppLayout>
      <section>
      <img src='/Logo.png' alt='Logo'></img>
        <h1> Devter</h1>
        <h2>Talk about development <br/> with developers 👨🏽‍💻👩🏽‍💻</h2>


        <div>
          <Button>
            <GitHub fill={'#fff'} width={32} height={24}/>
            Login with GitHub</Button>
        </div>


      </section>
     </AppLayout>
    <style jsx>{`
      img {
        width: 120px;
      }

      section{
        display: grid;
        height: 100%;
        place-content: center;
        place-items: center;
        
      }

      div{
        margin-top: 16px
      }

      h1{
        color: ${colors.secondary};
        font-weigth: 800;
        margin-bottom: 16px;
      }

      h2{
        color: ${colors.primary};
        font-size: 21px;
        margin: 0;
      }
     `}
    </style>
    </>
  )
}
